[package]
name = "ferric_cache"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
libc = "0.2"
rand = "0.8"
cfg-if = "1.0"
crossbeam-queue = "0.3"
crossbeam-channel = "0.5"

[features]
default = []
libaio = []
capi = []
